/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me10zyl_doc_generator_opacity_WindowMoveListener */

#ifndef _Included_com_me10zyl_doc_generator_opacity_WindowMoveListener
#define _Included_com_me10zyl_doc_generator_opacity_WindowMoveListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me10zyl_doc_generator_opacity_WindowMoveListener
 * Method:    startWindowMoveListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_me10zyl_doc_1generator_opacity_WindowMoveListener_startWindowMoveListener
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
